version: '3.8'

services:
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8007
    command: gunicorn games_project.wsgi:application --bind 0.0.0.0:8007 --workers 4
    volumes:
      - .:/code
    ports:
      - "8007:8007"